"""ver0.1

Revision ID: 240536d4ad16
Revises: 
Create Date: 2019-10-25 23:00:13.121094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240536d4ad16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('over', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('engines',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('weapons',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('fighters',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('number_built', sa.Integer(), nullable=True),
    sa.Column('generation', sa.String(length=40), nullable=True),
    sa.Column('number_of_engine', sa.Integer(), nullable=True),
    sa.Column('designedby', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['designedby'], ['companies.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('models',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('first_flight', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('fighter_name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['fighter_name'], ['fighters.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('equippedwithengines',
    sa.Column('fighter_name', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('engine_name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['engine_name'], ['engines.name'], ),
    sa.ForeignKeyConstraint(['fighter_name'], ['fighters.name'], ),
    sa.ForeignKeyConstraint(['model_name'], ['models.name'], ),
    sa.PrimaryKeyConstraint('fighter_name', 'model_name', 'engine_name')
    )
    op.create_table('equippedwithweapons',
    sa.Column('fighter_name', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('weapon_name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['fighter_name'], ['fighters.name'], ),
    sa.ForeignKeyConstraint(['model_name'], ['models.name'], ),
    sa.ForeignKeyConstraint(['weapon_name'], ['weapons.name'], ),
    sa.PrimaryKeyConstraint('fighter_name', 'model_name', 'weapon_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equippedwithweapons')
    op.drop_table('equippedwithengines')
    op.drop_table('models')
    op.drop_table('fighters')
    op.drop_table('weapons')
    op.drop_table('engines')
    op.drop_table('companies')
    # ### end Alembic commands ###
