"""re update db

Revision ID: 2bfbee3d5e49
Revises: 240536d4ad16
Create Date: 2019-10-29 00:21:03.421028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bfbee3d5e49'
down_revision = '240536d4ad16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'country',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('companies', 'start',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('engines', 'country',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('engines', 'year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('EQUIPPEDWITH_ENGINES', 'equippedwithengines', type_='foreignkey')
    op.drop_constraint('MODELS_EQUIPPEDWITH2', 'equippedwithengines', type_='foreignkey')
    op.drop_constraint('FIGHTERS_HAVE2', 'equippedwithengines', type_='foreignkey')
    op.create_foreign_key(None, 'equippedwithengines', 'fighters', ['fighter_name'], ['name'])
    op.create_foreign_key(None, 'equippedwithengines', 'engines', ['engine_name'], ['name'])
    op.create_foreign_key(None, 'equippedwithengines', 'models', ['model_name'], ['name'])
    op.drop_constraint('MODELS_EQUIPPEDWITH1', 'equippedwithweapons', type_='foreignkey')
    op.drop_constraint('EQUIPPEDWITH_WEAPONS', 'equippedwithweapons', type_='foreignkey')
    op.drop_constraint('FIGHTERS_HAVE1', 'equippedwithweapons', type_='foreignkey')
    op.create_foreign_key(None, 'equippedwithweapons', 'weapons', ['weapon_name'], ['name'])
    op.create_foreign_key(None, 'equippedwithweapons', 'fighters', ['fighter_name'], ['name'])
    op.create_foreign_key(None, 'equippedwithweapons', 'models', ['model_name'], ['name'])
    op.alter_column('fighters', 'designedby',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('fighters', 'generation',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('fighters', 'number_built',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('fighters', 'number_of_engine',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('COMPANIES_DESIGNE', 'fighters', type_='foreignkey')
    op.create_foreign_key(None, 'fighters', 'companies', ['designedby'], ['name'])
    op.alter_column('models', 'fighter_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('models', 'first_flight',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('models', 'status',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.drop_constraint('modelof', 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'fighters', ['fighter_name'], ['name'])
    op.alter_column('weapons', 'country',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('weapons', 'type',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('weapons', 'year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weapons', 'year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('weapons', 'type',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('weapons', 'country',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key('modelof', 'models', 'fighters', ['fighter_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('models', 'status',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('models', 'first_flight',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('models', 'fighter_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.drop_constraint(None, 'fighters', type_='foreignkey')
    op.create_foreign_key('COMPANIES_DESIGNE', 'fighters', 'companies', ['designedby'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('fighters', 'number_of_engine',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fighters', 'number_built',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('fighters', 'generation',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('fighters', 'designedby',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.drop_constraint(None, 'equippedwithweapons', type_='foreignkey')
    op.drop_constraint(None, 'equippedwithweapons', type_='foreignkey')
    op.drop_constraint(None, 'equippedwithweapons', type_='foreignkey')
    op.create_foreign_key('FIGHTERS_HAVE1', 'equippedwithweapons', 'fighters', ['fighter_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('EQUIPPEDWITH_WEAPONS', 'equippedwithweapons', 'weapons', ['weapon_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('MODELS_EQUIPPEDWITH1', 'equippedwithweapons', 'models', ['model_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'equippedwithengines', type_='foreignkey')
    op.drop_constraint(None, 'equippedwithengines', type_='foreignkey')
    op.drop_constraint(None, 'equippedwithengines', type_='foreignkey')
    op.create_foreign_key('FIGHTERS_HAVE2', 'equippedwithengines', 'fighters', ['fighter_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('MODELS_EQUIPPEDWITH2', 'equippedwithengines', 'models', ['model_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('EQUIPPEDWITH_ENGINES', 'equippedwithengines', 'engines', ['engine_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('engines', 'year',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('engines', 'country',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('companies', 'start',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('companies', 'country',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
